---
title: Desert Jewels Nursery
timezone: America/Los_Angeles
permalink: pretty
url: https://jeking123.github.io/desertjewelsnursery
plugins:
- jekyll-sitemap
collections:
  posts:
    title: Posts
    output: true
    heading: Have you read our latest blog posts?
  uploads:
    title: Uploads
    output: true
  inventory:
    title: Inventory
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author: John Doe
    image: 
- scope:
    path: ''
    type: inventory
  values:
    layout: inventory-update
    permalink: "/inventory/:file/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
